pipeline:
  build:
    image: maven
    commands:
      - curl -O https://archive.apache.org/dist/ranger/${RELEASE}/apache-ranger-${RELEASE}.tar.gz
      - tar zxf apache-ranger-${RELEASE}.tar.gz
      - chmod +x build.sh
      - cd apache-ranger-${RELEASE}
      - ../build.sh

  webhook:
    image: septianw/droneteleg:init
    token: ${TELETOKEN}
    channel: butlerjob

matrix:
  RELEASE:
    - 0.6.3
    - 0.7.0
    - 0.7.1
