pipeline:
  build:
    image: maven
    commands:
      - curl -O https://archive.apache.org/dist/incubator/ranger/0.5.0-incubating/ranger-0.5.0-incubating.tar.gz
      - tar zxf ranger-0.5.0-incubating.tar.gz
      - cd apache-ranger-0.5.0
      - mvn clean
      - mvn -DskipTests=false clean compile package install assembly:assembly
